#//Title: stephens-composer.yaml
#//Author: Kailee Stephens
#//Date: 28 August 2022
#//Description: OpenAPI description


openapi: 3.0.0
info:
  title: Person's API
  version: "1.0"

servers:
  - url: https://localhost:3000/
    description: Main (production) server
paths:
  /api/persons:
    get:
      summary: Returns a list of all.
      description: |
        Returns a list of all people in catalog.
      responses:
        '200':    # status code
          description: A JSON array of person names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '500':    # status code
          description: Server exceptions
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string    
        '501':    # status code
          description: MongoDB exceptions
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    post:
      summary: Creates a new person.
      description: |
        Creates and adds a new person to the catalog.
      responses:
        '200':    # status code
          description: A JSON array for new person.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '500':    # status code
          description: Server exceptions
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string    
        '501':    # status code
          description: MongoDB exceptions
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
